# Generated by Django 5.2 on 2025-07-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='sellers/banners/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='sellers/ids/')),
                ('artisan_certificate', models.FileField(blank=True, null=True, upload_to='sellers/certificates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('average_rating', models.FloatField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
